# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dptf <- function(y, lam) {
    .Call(`_gaussdeconv_dptf`, y, lam)
}

weight_dptf <- function(y, lam, w) {
    .Call(`_gaussdeconv_weight_dptf`, y, lam, w)
}

estim_path <- function(y, x, w, korder, lambda, lambdamax = -1, lambdamin = -1, nsol = 100L, rho = -1, maxiter = 1e5L, tolerance = 1e-3, lambda_min_ratio = 1e-4, verbose = 0L) {
    .Call(`_gaussdeconv_estim_path`, y, x, w, korder, lambda, lambdamax, lambdamin, nsol, rho, maxiter, tolerance, lambda_min_ratio, verbose)
}

get_Dtil <- function(k, xd) {
    .Call(`_gaussdeconv_get_Dtil`, k, xd)
}

get_D <- function(k, xd) {
    .Call(`_gaussdeconv_get_D`, k, xd)
}

create_lambda_test <- function(lambda, lambdamin, lambdamax, lambda_min_ratio, nsol) {
    .Call(`_gaussdeconv_create_lambda_test`, lambda, lambdamin, lambdamax, lambda_min_ratio, nsol)
}

doDv <- function(v, k, xd) {
    .Call(`_gaussdeconv_doDv`, v, k, xd)
}

doDtv <- function(v, k, xd) {
    .Call(`_gaussdeconv_doDtv`, v, k, xd)
}

